# Academic Honesty

In the event of an unexpected campus closure or delayed start, course requirements, deadlines and grading percentages are subject to change when necessitated by revised course delivery, semester calendar or other circumstances. Information about changes in this course can be obtained on the Blackboard course homepage or by contacting my email address: xxxx@lc.edu or office phone/cell xxx-xxx-xxxx. If the course is not able to meet face-to-face, students should immediately log onto L&C Blackboard, https://blackboard.lc.edu, and read any announcements and/or alternative assignments. Students are also encouraged to continue the readings and other assignments as outlined on this syllabus or subsequent syllabi.

## L&C Policy on Academic Honesty: Cheating.

Intentionally using or attempting to use unauthorized materials, information or study aids; use of any unauthorized assistance, resources, materials or electronic/cellular devices with or without photographic capability in taking quizzes, tests or examinations and the acquisition, without permission, of a test or other academic material belonging to Lewis & Clark Community College, to any department, or to any staff.

## Plagiarism:

Plagiarism at LCCC will not be tolerated. Plagiarism includes the reproduction of ideas, words or statements of another person as ones’ own without acknowledgement or use of an agency engaged in the selling of term papers or other academic materials. If instructor has reason to believe students are in violation of this policy, students will be notified and appropriate action will be taken.

## LCCC Plagiarism statement:

Assignments that have been copied from another student or another source will not be scored. “Academic dishonesty including, but not limited to, cheating, plagiarism, and forgery, violates the STUDENT CONDUCT CODE and will lead to disciplinary action up to and including expulsion”. The following website will give you in-depth information on the definition of plagiarism and more: http://www.plagiarism.org/article/what-is-plagiarism Please visit this site if you need clarification.

## Unauthorized Collaboration:

Unauthorized collaboration among students will not be tolerated. Unauthorized collaboration is defined as intentionally sharing or working together in an academic exercise when such actions are not approved by the course instructor. Academic exercises include but are not limited to all face-to-face and/or online classroom assignments, activities, exams, quizzes, worksheets, online discussion questions, term papers, case studies, projects, research, or any other requirement assigned by the instructor for which students receive individual grades. If the instructor has reason to believe students share or work together collaboratively on such academic exercises, the student(s) will be notified and at the minimum, receive a zero on the assignment.

## Facilitation of Academic Dishonesty:

Permitting or attempting to help another to violate the academic honor code; Alteration or sabotage of another student's work, such as tampering with or modifying any online or written assignments including but not limited to quizzes, exams, worksheets, term papers, case studies, projects, research, discussion board entries, etc. If the instructor has reason to believe students facilitate academic dishonesty, the student(s) will be notified and appropriate action will be taken.
