# Diversity Statement

At Lewis and Clark Community College, we are seriously committed to supporting diversity and inclusion in our classrooms and community. We proactively strive to construct a safe and inclusive environment by respecting each other’s dignity and privacy. We treat one another fairly and honor each member’s experiences, beliefs, perspectives, abilities, and backgrounds, regardless of race, religion, language, immigration status, sexual orientation, gender identification, ability status, socio-economic status, national identity, or any other identity markers. Bullying, hateful ideas, violent language, belittling, racial slurs, and other disrespectful or “othering” language or behavior will not be tolerated. We behave and communicate respectfully toward one another, both directly and indirectly, both inside and outside the classroom. A diverse and inclusive campus is our strength, and we want all who are part of our campus community to feel safe and respected. If you ever have any concerns about the classroom climate, please reach out to Mya Lawrence, Director of Diversity, Equity, and Inclusive Excellence, NU L134, 618-468- 6030, mylawrence@lc.edu
