# Title IX

Lewis and Clark Community College is committed to maintaining a safe and healthy educational and employment environment that is free from sex discrimination, which includes discrimination and harassment based on sex, sex stereotypes, sex characteristics, pregnancy and related conditions, sexual orientation, and gender-related identity and expression. The College also prohibits all forms of sex-based misconduct, including but not limited to sexual violence, domestic violence, dating violence, and stalking. Faculty are legally required to report incidents of sex discrimination or misconduct brought to their attention through any sources and thus cannot guarantee confidentiality. To file a complaint, contact Sean Hill, Title IX Coordinator, at shill@lc.edu or 618-468-6000; or Mya Lawrence, Deputy Title IX Coordinator, at mylawrence@lc.edu or 618-468-6030. Students who wish to confidentially report an incident of sex discrimination may contact Terri Austin, Counselor, at taaustin@lc.edu or 618-468-4125; or Brooke Frank, Case Coordinator, at bfrank@lc.edu or 618-468-4130. Students can also leave an anonymous message on the college’s toll-free number for reporting sexual violence at 855-RSV- 4RSV (855-778-4778) or send an email to 4rsv@lc.edu. Please visit https://www.lc.edu/4RSV for more information.
